### ISSUE TITLE
Unable to decrypt with documented example

### ISSUE THREAD

**Issue by mitom** [aws/aws-encryption-sdk-python#305]
Hi,

I've been banging my head against the wall trying to figure it out but didn't get anywhere. The [example](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/python-example-code.html#python-example-strings) provided in the docs doesn't seem to work. The encryption happens, the decryption fails with:
```
Error on closing
Traceback (most recent call last):
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/__init__.py", line 162, in decrypt
    plaintext = decryptor.read()
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 246, in read
    self._prep_message()
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 774, in _prep_message
    self._header, self.header_auth = self._read_header()
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 810, in _read_header
    decryption_materials = self.config.materials_manager.decrypt_materials(request=decrypt_materials_request)
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/materials_managers/default.py", line 150, in decrypt_materials
    data_key = self.master_key_provider.decrypt_data_key_from_list(
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/key_providers/base.py", line 288, in decrypt_data_key_from_list
    raise DecryptKeyError("Unable to decrypt any data key")
aws_encryption_sdk.exceptions.DecryptKeyError: Unable to decrypt any data key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 214, in __exit__
    self.close()
  File "/Users/tamasmillian/.pyenv/versions/infra_deploy/lib/python3.8/site-packages/aws_encryption_sdk/streaming_client.py", line 975, in close
    raise SerializationError("Footer not read")
aws_encryption_sdk.exceptions.SerializationError: Footer not read
```

To test it, all I did was copy the exact contents from the string example and call it with
```
cycle_string("arn:aws:kms:us-east-1:<accountid>:alias/<myalias>", "test")
```

I assume it is not an issue with credentials since in the same shell without any change, I can use the cli to encrypt/decrypt a file with the same key.

Any help to point out what am I doing wrong?

**Comment by farleyb-amazon** [comment]
Hi mitom,

As you correctly pointed out, when decrypting a ciphertext you’ll need to provide the key ARN of the key used to encrypt it; neither an alias name nor an alias ARN will work. If that doesn’t work for your use case, you can consider using a `DiscoveryAwsKmsKeyProvider` which will allow decryption without specifying the key id. If you do that, we recommend using a `DiscoveryFilter` to limit decryption to only explicit AWS accounts and AWS partitions. 

As for the CLI, it should behave the same way. However, there was a bug in previous versions of the CLI which did not correctly implement strict and discovery modes. The most recent versions (1.8.x and 2.1.x) have fixed this, so if you update
your CLI you should see the same behavior as you see in the Python Encryption SDK. 

You can see more details on the CLI issue here: https://github.com/aws/aws-encryption-sdk-cli/security/advisories/GHSA-2xwp-m7mq-7q3r
