### ISSUE TITLE
[ERROR] SerializationError: ('Unexpected deserialization error', <class 'struct.error'>, ('unpack requires a buffer of 4112 bytes',))

### ISSUE THREAD

**Issue by rednibia** [aws/aws-encryption-sdk-python#330]
We have seen this error inconsistently when decrypting from inside a lambda. We are going to increase the size of our lambda's memory under the suspicion that the error is being cause by a lack of memory, but are unsure that this is the culprit based on the being thrown alone. We do not believe it is a data or code issue as we have pushed that exact same data through again using the exact same code successfully. Any input would be helpful.

    [ERROR] SerializationError: ('Unexpected deserialization error', <class 'struct.error'>, ('unpack requires a buffer of 4112 bytes',))
    Traceback (most recent call last):
      File "/var/task/lambda_function.py", line 53, in lambda_handler
        for record in s3_helper.s3_firehose_record_iter(source_bucket, source_s3_key, s3_encryption):
      File "/opt/python/s3_helper.py", line 42, in s3_firehose_record_iter
        decrypted_contents = encryption.decrypt_contents(record)
      File "/opt/python/lib/python3.7/site-packages/encryption_helper.py", line 52, in decrypt_contents
        materials_manager=self.caching_cmm)
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/__init__.py", line 162, in decrypt
        plaintext = decryptor.read()
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/streaming_client.py", line 257, in read
        line = self.readline()
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/streaming_client.py", line 289, in readline
        line = self.read(self.line_length)
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/streaming_client.py", line 252, in read
        self._read_bytes(b)
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/streaming_client.py", line 965, in _read_bytes
        self.output_buffer += self._read_bytes_from_framed_body(b)
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/streaming_client.py", line 920, in _read_bytes_from_framed_body
        stream=self.source_stream, header=self._header, verifier=self.verifier
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 469, in deserialize_frame
        verifier,
      File "/opt/python/lib/python3.7/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 518, in unpack_values
        raise SerializationError("Unexpected deserialization error", type(error), error.args)

**Comment by alex-chew** [comment]
Hi rednibia, thanks for reaching out.

This isn't an error case we've seen before, and it does seem unusual that the same data and same code have also worked for you. Can you try increasing the size of your Lambda function's memory as you suggest, and let us know how that goes? It would also help if you can provide a code snippet from where you're calling the Encryption SDK APIs, and details about the Lambda environment where you're running the code.

Thanks!

**Comment by abdallahalsalmi** [comment]
Just writing to say I'm getting the same error: 

```SerializationError("Unexpected deserialization error", "<class 'struct.error'>", "('unpack requires a buffer of 1 `bytes',)")```

Although I'm decrypting from an EC2 instance. Encryption worked fine. I'm using the 4.1 version.

**Comment by texastony** [comment]
Howdy @abdallahalsalmi ,
Is this a consistent error or is it inconsistent like the error described by @rednibia ?
Is it possible that this is a network error?
My thought is that the encrypted data is being truncated by a network interruption. But I know too little to make an informed guess...
Can you share any other details? Are these encrypted objects being streamed from an event or are they already present on disk? Anything that can help us reproduce this error would be much appreciated.

**Comment by abdallahalsalmi** [comment]
Hi I found the problem. The S3 bucket I was trying to get encrypted content from had already been encrypted by a different CMK. That's why it was throwing these errors. It worked fine when I used a new bucket.

I did raise a separate ticket: https://github.com/aws/aws-encryption-sdk-python/issues/385

I think the ticket should be closed/deleted because it's not related to aws-encryption-sdk.

**Comment by alex-chew** [comment]
Hi @rednibia,

As we haven't heard from you in a while, we're going to go ahead and close this issue. If you have any further questions or concerns, please feel free to re-open this issue or open a new one.
