### ISSUE TITLE
Error decrypting Kinesis data key

### ISSUE THREAD

**Issue by cbebekjsonar** [aws/aws-encryption-sdk-python#334]
I'd appreciate any help, working with:
`aws-encryption-sdk-cli/2.1.0 aws-encryption-sdk/2.0.0`

trying to decrypt a data key from a kinesis stream with my CMK gives:

`NotSupportedError("Unsupported type 2 discovered in data stream", "2 is not a valid ObjectType")`

Trying with:

`echo 'AQID...2Q==' | base64 -d | aws-encryption-cli --decrypt --input - --wrapping-keys key=arn:aws:kms:XXXX:YYYY:key/ZZZZ --output decrypted_data_key --suppress-metadata`

**Comment by cbebekjsonar** [comment]
with verbosity:

`NotSupportedError("Unsupported type 2 discovered in data stream", "2 is not a valid ObjectType")
2021-04-18 17:52:09,289 - MainThread - aws_encryption_sdk_cli - DEBUG - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 101, in _verified_message_type_from_id
    return ObjectType(message_type_id)
  File "/usr/lib64/python3.6/enum.py", line 293, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib64/python3.6/enum.py", line 535, in __new__
    return cls._missing_(value)
  File "/usr/lib64/python3.6/enum.py", line 548, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 2 is not a valid ObjectType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/__init__.py", line 283, in cli
    process_cli_request(stream_args, args)
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/__init__.py", line 193, in process_cli_request
    stream_args=stream_args, source=parsed_args.input, destination=parsed_args.output
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 275, in process_single_operation
    stream_args=stream_args, source=cast(IO, source), destination_writer=destination_writer
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk_cli/internal/io_handling.py", line 216, in _single_io_write
    header=json_ready_header(handler.header),
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py", line 204, in header
    self._prep_message()
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py", line 774, in _prep_message
    self._header, self.header_auth = self._read_header()
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/streaming_client.py", line 788, in _read_header
    header, raw_header = deserialize_header(self.source_stream)
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 331, in deserialize_header
    return _deserialize_header_v1(header, tee_stream), tee.getvalue()
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 246, in _deserialize_header_v1
    header["type"] = _verified_message_type_from_id(message_type_id)
  File "/usr/local/lib/python3.6/site-packages/aws_encryption_sdk/internal/formatting/deserialize.py", line 103, in _verified_message_type_from_id
    raise NotSupportedError("Unsupported type {} discovered in data stream".format(message_type_id), error)
aws_encryption_sdk.exceptions.NotSupportedError: ('Unsupported type 2 discovered in data stream', ValueError('2 is not a valid ObjectType',))`

**Comment by farleyb-amazon** [comment]
Hi,

That error message typically means the ciphertext trying to be decrypted is incorrectly formatted. As a sanity check, I used the CLI to encrypt a file and then used your example command line invocation to decrypt it and it succeeded, so your command looks good.

Can you clarify how the encrypted records in the Kinesis data stream are being generated? Are they encrypted with the AWS Encryption SDK, either the CLI or another supported language?

Thanks,
Ben

**Comment by cbebekjsonar** [comment]
Hi Ben, thanks for responding

The source is Aurora w/Kinesis. Turns out I was missing the encryption-context. Getting a record returns:
```
{"type":"DatabaseActivityMonitoringRecords",
"version":"1.0",
"databaseActivityEvents":"XXXXXXX",
"key":"ABCD.....=="}
```

and I can get a plaintext data key with:
```
aws kms decrypt \
--ciphertext-blob fileb://<(echo 'ABCD==' | base64 -d) \
--encryption-context aws:rds:dbc-id=cluster-YYYY \
--output text \
--query Plaintext
```
But still not sure how to use aws-encryption-cli to decrypt "databaseActivityEvents" with the plaintext data key. Should this be possible on Aurora Kinesis streams?

**Comment by cbebekjsonar** [comment]
I was trying to follow here:

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/DBActivityStreams.Monitoring.html

they say

"Decrypt the binary ciphertext with the data encryption key that you decoded in the first step"

without much further help of example

**Comment by sslathia** [comment]
@cbebekjsonar  can you let me know what script you used i am getting a error botocore.errorfactory.InvalidCiphertextException: An error occurred (InvalidCiphertextException) when calling the Decrypt operation:
i am trying to decrept the key with master key

**Comment by mseenivasahan** [comment]
> yes, I ended up using a python script, thanks

I followed the same but ended up invalidcipher exception while calling kms.decrypt.. key is passed as decoded bytes as need.. any special permission required?? Pls advise
