### ISSUE TITLE
AttributeError while running examples in this repo

### ISSUE THREAD

**Issue by nbommu1** [aws/aws-encryption-sdk-python#58]
Hi, 

when I'm running examples from this repo "Encryption and Decryption" , this gives me the following error.

```
Traceback (most recent call last):
  File "kms-multi.py", line 11, in <module>
    key_provider=kms_key_provider
  File "/home/nbommu/python/local/lib/python2.7/site-packages/aws_encryption_sdk/__init__.py", line 76, in encrypt
    ciphertext = encryptor.read()
  File "/home/nbommu/python/local/lib/python2.7/site-packages/aws_encryption_sdk/streaming_client.py", line 202, in read
    self._prep_message()
  File "/home/nbommu/python/local/lib/python2.7/site-packages/aws_encryption_sdk/streaming_client.py", line 405, in _prep_message
    request=encryption_materials_request
  File "/home/nbommu/python/local/lib/python2.7/site-packages/aws_encryption_sdk/materials_managers/default.py", line 78, in get_encryption_materials
    signing_key = self._generate_signing_key_and_update_encryption_context(algorithm, encryption_context)
  File "/home/nbommu/python/local/lib/python2.7/site-packages/aws_encryption_sdk/materials_managers/default.py", line 54, in _generate_signing_key_and_update_encryption_context
    if algorithm.signing_algorithm_info is None:
AttributeError: 'tuple' object has no attribute 'signing_algorithm_info'
```

Name: Python
Version: 2.7.14
Name: boto3
Version: 1.7.48

**Comment by mattsb42-aws** [comment]
Could you provide the code that you ran when you got this error? This looks like it might have been caused by a malformed input parameter but it's tell without seeing the code.

**Comment by nbommu1** [comment]
this is the example code I'm using in my test.

import aws_encryption_sdk

kms_key_provider = aws_encryption_sdk.KMSMasterKeyProvider(key_ids=[
    'arn:aws:kms:us-east-1:2222222222222:key/22222222-2222-2222-2222-222222222222',
    'arn:aws:kms:us-east-1:3333333333333:key/33333333-3333-3333-3333-333333333333'
])
my_plaintext = 'This is some super secret data!  Yup, sure is!'

my_ciphertext, encryptor_header = aws_encryption_sdk.encrypt(
    source=my_plaintext,
    key_provider=kms_key_provider
)

decrypted_plaintext, decryptor_header = aws_encryption_sdk.decrypt(
    source=my_ciphertext,
    key_provider=kms_key_provider
)

**Comment by mattsb42-aws** [comment]
Sorry for the delay.

This is a very odd error and seems like something going wrong deep inside somewhere; maybe something wrong with `Enum34`? Could you show the output of `pip freeze` and I can try to replicate this?

**Comment by mattsb42-aws** [comment]
Sorry, @nbommu1, this fell off my radar. Did you ever figure out the issue you were having? I tried installing that freeze file in a new virtualenv with CPython 2.7.14 and running the example code you specified, and it worked for me.

**Comment by mattsb42-aws** [comment]
Closing due to inactivity. If you are still having issues, @nbommu1, please feel free to re-open.
